window.addEventListener("error", (event) => {
  console.error("Hotdeal Radar error:", event.error || event.message);
  const empty = document.querySelector("#emptyState");
  if (empty) {
    empty.classList.remove("hidden");
    empty.textContent = "화면 표시 중 오류가 발생했습니다. app.js와 styles.css가 최신 버전인지 확인해주세요.";
  }
});

const state={deals:[],sources:[],mode:"all",category:"전체",source:"전체",query:"",sort:"score",price:"all",hideEnded:true};
const cats={"전체":[],"식품·간식":["식품","간식","커피","라면","쌀","고기","과자","음료","밀키트","냉동"],"생필품":["세제","휴지","물티슈","청소","욕실","샴푸","치약","건전지"],"주방·수납":["주방","수납","정리함","냄비","프라이팬","식기","텀블러"],"육아":["육아","기저귀","분유","이유식","아기","젖병","카시트","유모차"],"반려동물":["반려","강아지","고양이","사료","배변패드","모래","펫"],"뷰티·건강":["뷰티","화장품","선크림","마스크팩","영양제","건강","향수"],"패션":["패션","의류","신발","패딩","무신사","운동화"],"IT·가전":["노트북","태블릿","SSD","충전기","케이블","마우스","키보드","에어컨","냉장고","청소기","TV","세탁기"],"상품권·포인트":["상품권","페이","쿠폰","적립","해피머니","컬쳐랜드"],"해외직구":["알리","AliExpress","테무","아마존","직구"]};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
document.addEventListener("DOMContentLoaded",()=>{setupActionLink();renderCategories();bind();loadData();});
function setupActionLink(){const a=$("#actionLink");const parts=location.hostname.split(".");const repo=location.pathname.split("/").filter(Boolean)[0]||"";a.href=(location.hostname.endsWith("github.io")&&repo)?`https://github.com/${parts[0]}/${repo}/actions/workflows/update-deals.yml`:"#";}
function bind(){ $("#refreshBtn").onclick=loadData; $("#searchInput").oninput=e=>{state.query=e.target.value.trim().toLowerCase();apply();}; $("#sortSelect").onchange=e=>{state.sort=e.target.value;apply();}; $("#priceSelect").onchange=e=>{state.price=e.target.value;apply();}; $("#hideEnded").onchange=e=>{state.hideEnded=e.target.checked;apply();}; $("#clearFilters").onclick=reset; $$("#modeTabs .chip").forEach(b=>b.onclick=()=>{$$("#modeTabs .chip").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.mode=b.dataset.mode;apply();});}
function reset(){state.mode="all";state.category="전체";state.source="전체";state.query="";state.sort="score";state.price="all";state.hideEnded=true;$("#searchInput").value="";$("#sortSelect").value="score";$("#priceSelect").value="all";$("#hideEnded").checked=true;$$(".chip").forEach(b=>b.classList.remove("active"));document.querySelector('[data-mode="all"]').classList.add("active");renderCategories();renderSources();apply();}
async function loadData(){try{const r=await fetch(`./data/deals.json?ts=${Date.now()}`);const p=await r.json();state.deals=(p.deals||[]).map(norm);$("#updatedAt").textContent=fmtDate(p.generated_at);}catch(e){console.error(e);state.deals=[];$("#updatedAt").textContent="오류";}try{const r=await fetch(`./data/sources.json?ts=${Date.now()}`);const p=await r.json();state.sources=p.sources||[];}catch(e){state.sources=[];}renderSources();renderStatus();try{apply();}catch(error){showRenderError(error);}}
function norm(d){const title=d.title||"제목 없음";const price=Number(d.price_value||extractPrice(title)||0);const flags=Array.isArray(d.flags)?d.flags:guessFlags(title);return {...d,id:d.id||String(Math.random()),title,category:d.category||guessCat(title),price_value:price,price_text:d.price_text||(price?price.toLocaleString()+"원":"가격 확인"),shop:d.shop||guessShop(title),source:d.source||"미분류",source_url:d.source_url||d.url||"#",purchase_url:d.purchase_url||"",purchase_domain:d.purchase_domain||"",score:Number(d.score||score(title,price,flags,d))||35,flags,created_at:d.created_at||new Date().toISOString()};}
function renderCategories(){const w=$("#categoryChips");w.innerHTML="";Object.keys(cats).forEach(c=>{const b=document.createElement("button");b.className="chip category-chip"+(c===state.category?" active":"");b.textContent=c;b.onclick=()=>{state.category=c;renderCategories();apply();};w.appendChild(b);});}
function renderSources(){const w=$("#sourceChips");w.innerHTML="";const names=["전체",...new Set([...state.sources.map(s=>s.name),...state.deals.map(d=>d.source)])];names.forEach(n=>{const s=state.sources.find(x=>x.name===n);const cnt=n==="전체"?state.deals.length:(s?s.count:state.deals.filter(d=>d.source===n).length);const b=document.createElement("button");b.className="chip source-chip"+(n===state.source?" active":"");if(s?.status==="failed")b.classList.add("error");if(["empty","disabled"].includes(s?.status))b.classList.add("warn");b.textContent=n==="전체"?"전체":`${n} ${cnt}`;b.onclick=()=>{state.source=n;renderSources();apply();};w.appendChild(b);});}
function renderStatus(){const w=$("#sourceStatus");if(!state.sources.length){w.innerHTML="<p>아직 수집처 상태 파일이 없어요.</p>";return;}w.innerHTML="";state.sources.forEach(s=>{const d=document.createElement("div");d.className=`source-row ${s.status||""}`;const label={ok:"정상",empty:"0건",failed:"실패",disabled:"비활성"}[s.status]||"확인";d.innerHTML=`<b>${esc(s.name)} · ${label}</b><span>${Number(s.count||0)}건 · 구매처 ${Number(s.purchase_count||0)}건 · ${esc(s.message||"")}</span>`;w.appendChild(d);});}
function apply(){let arr=state.deals.filter(d=>{const text=`${d.title} ${d.category} ${d.shop} ${d.source}`.toLowerCase();if(state.query&&!text.includes(state.query))return false;if(state.source!=="전체"&&d.source!==state.source)return false;if(state.category!=="전체"&&!hasAny(d,cats[state.category]))return false;if(state.hideEnded&&d.flags.some(f=>["종료","품절"].includes(f)))return false;if(state.mode==="purchase"&&!d.purchase_url)return false;if(state.mode==="under10000"&&!(d.price_value>0&&d.price_value<=10000))return false;if(state.mode==="daily"&&!hasAny(d,[...cats["식품·간식"],...cats["생필품"],...cats["주방·수납"]]))return false;if(state.mode==="baby"&&!hasAny(d,cats["육아"]))return false;if(state.mode==="tech"&&!hasAny(d,cats["IT·가전"]))return false;if(state.mode==="pet"&&!hasAny(d,cats["반려동물"]))return false;if(state.mode==="beauty"&&!hasAny(d,cats["뷰티·건강"]))return false;if(state.price==="under10000"&&!(d.price_value>0&&d.price_value<=10000))return false;if(state.price==="under30000"&&!(d.price_value>0&&d.price_value<=30000))return false;if(state.price==="under100000"&&!(d.price_value>0&&d.price_value<=100000))return false;return true;});arr=sort(arr);renderSummary(arr);safeRenderDeals(arr);}
function sort(a){a=[...a];if(state.sort==="new")a.sort((x,y)=>new Date(y.created_at)-new Date(x.created_at));else if(state.sort==="priceLow")a.sort((x,y)=>(x.price_value||999999999)-(y.price_value||999999999));else if(state.sort==="purchase")a.sort((x,y)=>(y.purchase_url?1:0)-(x.purchase_url?1:0)||y.score-x.score);else a.sort((x,y)=>y.score-x.score);return a;}
function renderSummary(arr){$("#totalCount").textContent=state.deals.length.toLocaleString();$("#purchaseCount").textContent=state.deals.filter(d=>d.purchase_url).length.toLocaleString();$("#underCount").textContent=state.deals.filter(d=>d.price_value>0&&d.price_value<=10000).length.toLocaleString();$("#resultCount").textContent=`${arr.length.toLocaleString()}개 딜`;}
function showRenderError(error){
  console.error(error);
  const list = $("#dealList");
  const empty = $("#emptyState");
  if (list) list.innerHTML = "";
  if (empty) {
    empty.classList.remove("hidden");
    empty.textContent = "딜 데이터는 불러왔지만 카드 표시 중 오류가 발생했습니다. index/app/styles 파일을 모두 v1.8로 교체해주세요.";
  }
}
function safeRenderDeals(arr){
  try {
    renderDeals(arr);
  } catch (error) {
    showRenderError(error);
  }
}
function renderDeals(arr){const list=$("#dealList"),empty=$("#emptyState");if(!list||!empty){return;}list.innerHTML="";empty.classList.toggle("hidden",arr.length>0);const t=$("#dealTemplate");if(!t||!t.content||!t.content.firstElementChild){throw new Error("dealTemplate missing");}arr.slice(0,140).forEach(d=>{d.flags=Array.isArray(d.flags)?d.flags:guessFlags(d.title||"");const n=t.content.firstElementChild.cloneNode(true);n.querySelector(".source").textContent=d.source;n.querySelector(".category").textContent=d.category;n.querySelector(".score").textContent=`${Math.round(d.score)}점`;n.querySelector(".title").textContent=d.title;n.querySelector(".price").textContent=d.price_text;n.querySelector(".shop").textContent=d.shop?`· ${d.shop}`:"";n.querySelector(".time").textContent=`· ${rel(d.created_at)}`;const fw=n.querySelector(".flags");d.flags.forEach(f=>{const s=document.createElement("span");s.className="flag";if(["인기","급상승"].includes(f))s.classList.add("hot");if(["무료배송","무료"].includes(f))s.classList.add("free");if(["종료","품절"].includes(f))s.classList.add("end");s.textContent=f;fw.appendChild(s);});const buy=n.querySelector(".buy");const origin=n.querySelector(".origin");buy.href=d.purchase_url||d.source_url||d.url||"#";buy.textContent=d.purchase_url?`구매처 바로가기${d.purchase_domain?" · "+d.purchase_domain:""}`:"구매처 미확인";if(!d.purchase_url)buy.classList.add("origin");origin.href=d.source_url||d.url||"#";n.querySelector(".copy").onclick=async()=>{await navigator.clipboard.writeText(d.purchase_url||d.source_url||d.url||"");n.querySelector(".copy").textContent="복사됨";setTimeout(()=>n.querySelector(".copy").textContent="복사",1200)};list.appendChild(n);});}
function hasAny(d,words){const text=`${d.title} ${d.category} ${d.shop}`.toLowerCase();return words.some(w=>text.includes(String(w).toLowerCase()));}function guessCat(t){for(const [c,ws] of Object.entries(cats)){if(c!=="전체"&&ws.some(w=>t.toLowerCase().includes(w.toLowerCase())))return c;}return"생필품";}function guessShop(t){return["쿠팡","네이버","지마켓","G마켓","옥션","11번가","롯데온","알리","SSG","무신사","하이마트","올리브영","다이소","테무","아마존"].find(s=>t.toLowerCase().includes(s.toLowerCase()))||"";}function guessFlags(t){const f=[];if(/무료배송|무배|무료/.test(t))f.push("무료배송");if(/품절|종료|마감/.test(t))f.push(t.includes("품절")?"품절":"종료");if(/역대가|핫딜|특가|체감가|쿠폰/.test(t))f.push("인기");if(extractPrice(t)>0&&extractPrice(t)<=10000)f.push("만원 이하");return f.length?f:["신규"];}function extractPrice(t){t=String(t).replace(/,/g,"");let m=t.match(/(\d+(?:\.\d+)?)\s*만\s*원?/);if(m)return Math.round(Number(m[1])*10000);m=t.match(/(\d{3,9})\s*원/);return m?Number(m[1]):0;}function score(t,p,f,d){let s=35;s+=Math.min(28,Number(d.likes||0)*1.2);s+=Math.min(18,Number(d.comments||0)*.6);s+=Math.min(12,Number(d.views||0)/2500);if(f.includes("무료배송"))s+=5;if(/역대가|특가|핫딜|쿠폰|무료/.test(t))s+=8;if(p>0&&p<=10000)s+=4;if(f.some(x=>["품절","종료"].includes(x)))s-=28;if(d.purchase_url)s+=6;return Math.max(1,Math.min(100,Math.round(s)));}function rel(v){const d=new Date(v);const m=Math.floor((Date.now()-d)/60000);if(isNaN(m))return"시간 확인";if(m<60)return`${Math.max(1,m)}분 전`;const h=Math.floor(m/60);if(h<24)return`${h}시간 전`;return`${Math.floor(h/24)}일 전`;}function fmtDate(v){const d=new Date(v);return isNaN(d)?"-":d.toLocaleString("ko-KR",{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"});}function esc(v){return String(v??"").replace(/[&<>"']/g,s=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[s]));}
